name: ${COMPOSE_PROJECT_NAME}

services:
  server:
    build:
      dockerfile: Dockerfile
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      API_SERVER_PORT: ${API_SERVER_PORT}
      API_VERSION: ${API_VERSION}
    ports:
      - ${API_SERVER_PORT}:${API_SERVER_PORT}
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
